### ISSUE TITLE
Assign Item Ids automatically

### ISSUE THREAD

**Issue by kamilaalv** [kamilaalv/GardenOfEden#4]
We need a method in some common interface(which needs to be created) to assign ids.

Ids for flowers, jewelry, and bouquets must be differentiable somehow (for example flower 0 - 100, bouquet 100 - 200, jewelry 200 - 300)
This is just an example in reality we would need more ids for flowers than for bouquets cuz bouquets consist of flowers.

U can add some constants in the options class for max num of ids for each type.
Also, u would need to keep track of the last id for each type

Ids should be reusable if u reached max, start from zero.

Constructors should be changed: 

1. Ids in parameter lists should be deleted. 
2. Call the method to assign id

Ps. Bouquets do not have ids in our implementation but I think we might need them for orders in the future. This is debatable. But we definitely need to assign ids for all items.

**Comment by YunoGasai9862** [comment]
Done caption!
